### ISSUE TITLE
Add header title / logo for hoster or faculty

### ISSUE THREAD

**Issue by PatrickSkowronek** [utetrapp/geli#236]
# User Story

### As a: 
User | Hoster

### I want:
to see who host the geli page or to which faculty does it belongs. 

### so that:

that i know that I'm on the right page

## Acceptance criteria:
- [ ] add a optional string in the header for the faculty or hoster 
- [ ] add a optional icon for the logo of the faculty or hoster

**Comment by OliverNeff** [comment]
Setting a textual logo under or next to our geli logo.

**Comment by PatrickSkowronek** [comment]
This can be closed. It was solved through #216
