### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by aeimer** [utetrapp/geli#522]
# User Story

### As a: 
Developer

### I want:
to have the latest possible depencies

### so that:
I have no Security Issues and the newest features

## Acceptance criteria:
- [ ] Update `api/package.json`
- [ ] Update `app/webFrontend/package.json`

## Additional info:
Have a look at the Travis build log, there are the dependencies listed, which are outdated. Be carefull with updating the main dependencies, like TypeScript, Angular and so on. This way the vulnerable `ssri`-dependency will disappear.

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by PatrickSkowronek** [comment]
This is currently in development #529

**Comment by PatrickSkowronek** [comment]
This can be closed for now.
