### ISSUE TITLE
"Impressum" translation

### ISSUE THREAD

**Issue by lukas-schardt** [utetrapp/geli#548]
# User Story

### As a(n): 
(international) geli user

### I want:
"Impressum" to be translated to "Legal notices", "About us" or something similar, or not to be translated at all.

### so that:
the translation is correct.

## Acceptance criteria:
- [x] The link https://geli.fbi.h-da.de/imprint is changed
- [x] The text translations where "imprint" is used are changed

## Additional info:

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by PatrickSkowronek** [comment]
This issue is related to #549

**Comment by aeimer** [comment]
You shouldn't change the url... thats a bad behaviour! You also can write an imprint in several languages and put them under each other. Normally a user who reads the imprint isn't logged in, so a translateable imprint is just nonsense, in my opinion.

**Comment by wurmc** [comment]
Will be solved with #768
