### ISSUE TITLE
cookie information

### ISSUE THREAD

**Issue by mleppla** [utetrapp/geli#565]
# User Story

### As a: 
visitor

### I want:
to be informed about cookies

### so that:
I know that the website uses cookies

## Acceptance criteria:
- [x] include cookie information

## Additional info:

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by PatrickSkowronek** [comment]
Please check if this is valid on all universities. May there are some which do not use numbers only!

**Comment by mleppla** [comment]
done, but wait for #768 to include a link with data protection in the cookie dialog
