### ISSUE TITLE
Keep other unit open

### ISSUE THREAD

**Issue by danielkesselberg** [utetrapp/geli#584]
# User Story

### As a: 

Teacher

### I want:

When opening a unit all other units are closed. I would like to keep other units open like in the student view. And close the unit only when hitting the arrow again.

![teacher_dont_collapse_units](https://user-images.githubusercontent.com/3902676/38441043-ad8ab880-39e3-11e8-9f61-54c5f3c8d0c7.PNG)

### so that:

Its easier to organize a course

## Acceptance criteria:
- [ ] Keep unit open when another unit is opened

**Comment by PatrickSkowronek** [comment]
This is closed through #726 !
