### ISSUE TITLE
Move create Course in a Dialog

### ISSUE THREAD

**Issue by PatrickSkowronek** [utetrapp/geli#725]
# User Story

## Acceptance criteria:
- [ ] Add a dialog
- [ ] Add name, description
- [ ] Accesstype
- [ ] viewable

**Comment by grosspersky** [comment]
I think that using a dialog for this is a direct violation of the material style guide, since dialogs should only be used for interruptive messages but never for things like content creation.
https://material.io/guidelines/components/dialogs.html
