### ISSUE TITLE
Add guided dialog for adding a whitelist

### ISSUE THREAD

**Issue by PatrickSkowronek** [utetrapp/geli#727]
# User Story

### I want: a guided dialog for adding a whitelist. 
Currently the feature is not that good, in a UX aspect. The dialog should be guided. So the screen is for uploading a file. The second screen should show the user, which are in geli and which are currently not. Also a accept or cancel button should be there. The functionality is present but the UI is not that good.

## Acceptance criteria:
- [ ] new dialog for whitelist feature
- [ ] use the shared upload component
- [ ] show the user at the end of the dialog
- [ ] don't create the whitelist user object in the db until the user accept

## Estimated:
- 5 x 4hr

**Comment by grosspersky** [comment]
I think that using a dialog for this is a direct violation of the material style guide, since dialogs should only be used for interruptive messages but never for things like content creation.
https://material.io/guidelines/components/dialogs.html

**Comment by PatrickSkowronek** [comment]
@lukas-schardt @MichaelNarkus Can you please close this too https://github.com/utetrapp/geli/issues/509 !

**Comment by PatrickSkowronek** [comment]
Maybe you could use this https://material.angular.io/components/stepper/overview
