### ISSUE TITLE
Add the possibility to add files directly in the file unit

### ISSUE THREAD

**Issue by PatrickSkowronek** [utetrapp/geli#728]
# User Story

## Acceptance criteria:
- [ ] the unit should have the shared upload-file component
- [ ] the added files should be added to the media manager
- [ ] selecting files from the media manager should be possible

**Comment by grosspersky** [comment]
Actually you should complete the media manager itself and upon creating a new file unit the manager should be opened with the possibility to upload or choose from existing libraries.

Maybe the the media manager from Drupal could serve as an inspiration:
![media-manager](https://user-images.githubusercontent.com/11839276/39776475-4b88a944-5301-11e8-89c1-95649d23db37.gif)

Except the usage of the dialog to display it. But feature-wise it would look similar to our planned behaviour.

Also note the backend is actually using a material inspired styling in this animation and the following screens:
![grafik](https://user-images.githubusercontent.com/11839276/39776604-a0565dae-5301-11e8-920c-962296ef3a83.png)
![grafik](https://user-images.githubusercontent.com/11839276/39776637-b322c21a-5301-11e8-878e-339a08b5f78c.png)

**Comment by Gargamil** [comment]
Maybe can be done with refactoring in #532
