### ISSUE TITLE
Large issue guideline creation

### ISSUE THREAD

**Issue by torss** [utetrapp/geli#747]
# User Story

### As a: 

Contributor

### I want:

GitHub issue organization guidelines for large issues

### so that:

one can efficiently keep track even of long-term goals in a standardized way.

## Acceptance criteria:
- [x] Create a guideline for handling large issues.
- [x] Create a new "tracking" label.

## Additional info:
This issue was _discovered_ as part of the geli development team retrospective on 2018-05-17.

**Comment by torss** [comment]
The initial draft can be found here: https://gist.github.com/torss/18809757f4ae2764030e532d53c62de7

**Comment by PatrickSkowronek** [comment]
I would put in the wiki!

**Comment by torss** [comment]
@PatrickSkowronek [Done](https://github.com/h-da/geli/wiki/Large-issue-guideline)! I first thought about adding it to the ["Best practices"](https://github.com/h-da/geli/wiki/Best-practices) page, but then decided to give the guideline its own page due to its relative length instead.
