### ISSUE TITLE
Certificate of https://demo.geli.fbi.h-da.de/ expired

### ISSUE THREAD

**Issue by mlsgit** [utetrapp/geli#814]
# User Story

### I want:
https://demo.geli.fbi.h-da.de/ with a valid certificate. :)

## Acceptance criteria:
- [ ]

**Comment by PatrickSkowronek** [comment]
Thanks! I will look this evening after it.

**Comment by PatrickSkowronek** [comment]
Done, it's working again. @mlsgit you can test it now. If anything else is not working please inform us.
